IT:
	chmod u+x Rit.r
	sudo ./Rit.r
SOCIETY:
	chmod u+x Rsociety.r
	sudo ./Rsociety.r
LIFE:
	chmod u+x Rlife.r
	sudo ./Rlife.r
POLITICS:
	chmod u+x Rpolitics.r
	sudo ./Rpolitics.r
ECONOMY:
	chmod u+x REconomy.r
	sudo ./REconomy.r
